/*
 * generated by Xtext 2.38.0
 */
package eu.coresense.variability.ide;


/**
 * Use this class to register ide components.
 */
public class VariabilityIdeModule extends AbstractVariabilityIdeModule {
}
