/*
 * generated by Xtext 2.38.0
 */
package eu.coresense.variability.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class VariabilityAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("eu/coresense/variability/parser/antlr/internal/InternalVariabilityParser.tokens");
	}
}
