/*
 * generated by Xtext 2.38.0
 */
package eu.coresense.variability.parser.antlr;

import com.google.inject.Inject;
import eu.coresense.variability.parser.antlr.internal.InternalVariabilityParser;
import eu.coresense.variability.services.VariabilityGrammarAccess;
import org.antlr.runtime.CharStream;
import org.antlr.runtime.TokenSource;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;

public class VariabilityParser extends AbstractAntlrParser {

	@Inject
	private VariabilityGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected TokenSource createLexer(CharStream stream) {
		return new VariabilityTokenSource(super.createLexer(stream));
	}
	
	/**
	 * Indentation aware languages do not support partial parsing since the lexer is inherently stateful.
	 * Override and return {@code true} if your terminal splitting is stateless.
	 */
	@Override
	protected boolean isReparseSupported() {
		return false;
	}

	@Override
	protected InternalVariabilityParser createParser(XtextTokenStream stream) {
		return new InternalVariabilityParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "System";
	}

	public VariabilityGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(VariabilityGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
