/*
 * generated by Xtext 2.38.0
 */
package eu.coresense.variability.ui.contentassist;

import de.fraunhofer.ipa.rossystem.ui.contentassist.RosSystemProposalProvider;

/**
 * Represents a generated, default implementation of superclass {@link RosSystemProposalProvider}.
 * Methods are dynamically dispatched on the first parameter, i.e., you can override them 
 * with a more concrete subtype. 
 */
public abstract class AbstractVariabilityProposalProvider extends RosSystemProposalProvider {

}
