/*
 * generated by Xtext 2.38.0
 */
package eu.coresense.variability.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class VariabilityUiModule extends AbstractVariabilityUiModule {

	public VariabilityUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
