/*
 * generated by Xtext 2.38.0
 */
package eu.coresense.variability.services;

import com.google.inject.Inject;
import com.google.inject.Singleton;
import de.fraunhofer.ipa.ros.services.BasicsGrammarAccess;
import de.fraunhofer.ipa.rossystem.services.RosSystemGrammarAccess;
import java.util.List;
import org.eclipse.xtext.Alternatives;
import org.eclipse.xtext.Assignment;
import org.eclipse.xtext.CrossReference;
import org.eclipse.xtext.Grammar;
import org.eclipse.xtext.GrammarUtil;
import org.eclipse.xtext.Group;
import org.eclipse.xtext.Keyword;
import org.eclipse.xtext.ParserRule;
import org.eclipse.xtext.RuleCall;
import org.eclipse.xtext.TerminalRule;
import org.eclipse.xtext.common.services.TerminalsGrammarAccess;
import org.eclipse.xtext.service.AbstractElementFinder;
import org.eclipse.xtext.service.GrammarProvider;

@Singleton
public class VariabilityGrammarAccess extends AbstractElementFinder.AbstractGrammarElementFinder {
	
	public class SystemElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "eu.coresense.variability.Variability.System");
		private final RuleCall cRosSystemParserRuleCall = (RuleCall)rule.eContents().get(1);
		
		//System returns System:
		//    RosSystem
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//RosSystem
		public RuleCall getRosSystemParserRuleCall() { return cRosSystemParserRuleCall; }
	}
	public class RosSystemElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "eu.coresense.variability.Variability.RosSystem");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cNameAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final RuleCall cNameEStringParserRuleCall_0_0 = (RuleCall)cNameAssignment_0.eContents().get(0);
		private final Keyword cColonKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final RuleCall cBEGINTerminalRuleCall_2 = (RuleCall)cGroup.eContents().get(2);
		private final Group cGroup_3 = (Group)cGroup.eContents().get(3);
		private final Keyword cFromFileKeyword_3_0 = (Keyword)cGroup_3.eContents().get(0);
		private final Assignment cFromFileAssignment_3_1 = (Assignment)cGroup_3.eContents().get(1);
		private final RuleCall cFromFileEStringParserRuleCall_3_1_0 = (RuleCall)cFromFileAssignment_3_1.eContents().get(0);
		private final Alternatives cAlternatives_4 = (Alternatives)cGroup.eContents().get(4);
		private final Group cGroup_4_0 = (Group)cAlternatives_4.eContents().get(0);
		private final Keyword cSubSystemsKeyword_4_0_0 = (Keyword)cGroup_4_0.eContents().get(0);
		private final RuleCall cBEGINTerminalRuleCall_4_0_1 = (RuleCall)cGroup_4_0.eContents().get(1);
		private final Assignment cComponentsAssignment_4_0_2 = (Assignment)cGroup_4_0.eContents().get(2);
		private final RuleCall cComponentsSubSystemParserRuleCall_4_0_2_0 = (RuleCall)cComponentsAssignment_4_0_2.eContents().get(0);
		private final RuleCall cENDTerminalRuleCall_4_0_3 = (RuleCall)cGroup_4_0.eContents().get(3);
		private final Group cGroup_4_1 = (Group)cAlternatives_4.eContents().get(1);
		private final Keyword cProcessesKeyword_4_1_0 = (Keyword)cGroup_4_1.eContents().get(0);
		private final RuleCall cBEGINTerminalRuleCall_4_1_1 = (RuleCall)cGroup_4_1.eContents().get(1);
		private final Assignment cProcessesAssignment_4_1_2 = (Assignment)cGroup_4_1.eContents().get(2);
		private final RuleCall cProcessesProcessParserRuleCall_4_1_2_0 = (RuleCall)cProcessesAssignment_4_1_2.eContents().get(0);
		private final RuleCall cENDTerminalRuleCall_4_1_3 = (RuleCall)cGroup_4_1.eContents().get(3);
		private final Group cGroup_4_2 = (Group)cAlternatives_4.eContents().get(2);
		private final Keyword cNodesKeyword_4_2_0 = (Keyword)cGroup_4_2.eContents().get(0);
		private final RuleCall cBEGINTerminalRuleCall_4_2_1 = (RuleCall)cGroup_4_2.eContents().get(1);
		private final Assignment cComponentsAssignment_4_2_2 = (Assignment)cGroup_4_2.eContents().get(2);
		private final RuleCall cComponentsRosNodeParserRuleCall_4_2_2_0 = (RuleCall)cComponentsAssignment_4_2_2.eContents().get(0);
		private final RuleCall cENDTerminalRuleCall_4_2_3 = (RuleCall)cGroup_4_2.eContents().get(3);
		private final Group cGroup_4_3 = (Group)cAlternatives_4.eContents().get(3);
		private final Keyword cParametersKeyword_4_3_0 = (Keyword)cGroup_4_3.eContents().get(0);
		private final RuleCall cBEGINTerminalRuleCall_4_3_1 = (RuleCall)cGroup_4_3.eContents().get(1);
		private final Assignment cParameterAssignment_4_3_2 = (Assignment)cGroup_4_3.eContents().get(2);
		private final RuleCall cParameterParameterParserRuleCall_4_3_2_0 = (RuleCall)cParameterAssignment_4_3_2.eContents().get(0);
		private final RuleCall cENDTerminalRuleCall_4_3_3 = (RuleCall)cGroup_4_3.eContents().get(3);
		private final Group cGroup_4_4 = (Group)cAlternatives_4.eContents().get(4);
		private final Keyword cConnectionsKeyword_4_4_0 = (Keyword)cGroup_4_4.eContents().get(0);
		private final RuleCall cBEGINTerminalRuleCall_4_4_1 = (RuleCall)cGroup_4_4.eContents().get(1);
		private final Assignment cConnectionsAssignment_4_4_2 = (Assignment)cGroup_4_4.eContents().get(2);
		private final RuleCall cConnectionsConnectionParserRuleCall_4_4_2_0 = (RuleCall)cConnectionsAssignment_4_4_2.eContents().get(0);
		private final RuleCall cENDTerminalRuleCall_4_4_3 = (RuleCall)cGroup_4_4.eContents().get(3);
		private final RuleCall cENDTerminalRuleCall_5 = (RuleCall)cGroup.eContents().get(5);
		
		//RosSystem returns System:
		//    name=EString':'
		//    BEGIN
		//        ('fromFile:' fromFile=EString)?
		//        (
		//        ('subSystems:'
		//            BEGIN
		//            components+=SubSystem*
		//            END
		//        ) |
		//        ('processes:'
		//            BEGIN
		//            processes+=Process*
		//            END
		//        ) |
		//        ('nodes:'
		//            BEGIN
		//            components+=RosNode*
		//            END
		//        ) |
		//        ('parameters:'
		//            BEGIN
		//            parameter+=Parameter*
		//            END
		//        ) |
		//        ('connections:'
		//            BEGIN
		//            connections+=Connection*
		//            END
		//        )
		//        )*
		//    END;
		@Override public ParserRule getRule() { return rule; }
		
		//name=EString':'
		//BEGIN
		//    ('fromFile:' fromFile=EString)?
		//    (
		//    ('subSystems:'
		//        BEGIN
		//        components+=SubSystem*
		//        END
		//    ) |
		//    ('processes:'
		//        BEGIN
		//        processes+=Process*
		//        END
		//    ) |
		//    ('nodes:'
		//        BEGIN
		//        components+=RosNode*
		//        END
		//    ) |
		//    ('parameters:'
		//        BEGIN
		//        parameter+=Parameter*
		//        END
		//    ) |
		//    ('connections:'
		//        BEGIN
		//        connections+=Connection*
		//        END
		//    )
		//    )*
		//END
		public Group getGroup() { return cGroup; }
		
		//name=EString
		public Assignment getNameAssignment_0() { return cNameAssignment_0; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_0_0() { return cNameEStringParserRuleCall_0_0; }
		
		//':'
		public Keyword getColonKeyword_1() { return cColonKeyword_1; }
		
		//BEGIN
		public RuleCall getBEGINTerminalRuleCall_2() { return cBEGINTerminalRuleCall_2; }
		
		//('fromFile:' fromFile=EString)?
		public Group getGroup_3() { return cGroup_3; }
		
		//'fromFile:'
		public Keyword getFromFileKeyword_3_0() { return cFromFileKeyword_3_0; }
		
		//fromFile=EString
		public Assignment getFromFileAssignment_3_1() { return cFromFileAssignment_3_1; }
		
		//EString
		public RuleCall getFromFileEStringParserRuleCall_3_1_0() { return cFromFileEStringParserRuleCall_3_1_0; }
		
		//(
		//('subSystems:'
		//    BEGIN
		//    components+=SubSystem*
		//    END
		//) |
		//('processes:'
		//    BEGIN
		//    processes+=Process*
		//    END
		//) |
		//('nodes:'
		//    BEGIN
		//    components+=RosNode*
		//    END
		//) |
		//('parameters:'
		//    BEGIN
		//    parameter+=Parameter*
		//    END
		//) |
		//('connections:'
		//    BEGIN
		//    connections+=Connection*
		//    END
		//)
		//)*
		public Alternatives getAlternatives_4() { return cAlternatives_4; }
		
		//('subSystems:'
		//    BEGIN
		//    components+=SubSystem*
		//    END
		//)
		public Group getGroup_4_0() { return cGroup_4_0; }
		
		//'subSystems:'
		public Keyword getSubSystemsKeyword_4_0_0() { return cSubSystemsKeyword_4_0_0; }
		
		//BEGIN
		public RuleCall getBEGINTerminalRuleCall_4_0_1() { return cBEGINTerminalRuleCall_4_0_1; }
		
		//components+=SubSystem*
		public Assignment getComponentsAssignment_4_0_2() { return cComponentsAssignment_4_0_2; }
		
		//SubSystem
		public RuleCall getComponentsSubSystemParserRuleCall_4_0_2_0() { return cComponentsSubSystemParserRuleCall_4_0_2_0; }
		
		//END
		public RuleCall getENDTerminalRuleCall_4_0_3() { return cENDTerminalRuleCall_4_0_3; }
		
		//('processes:'
		//    BEGIN
		//    processes+=Process*
		//    END
		//)
		public Group getGroup_4_1() { return cGroup_4_1; }
		
		//'processes:'
		public Keyword getProcessesKeyword_4_1_0() { return cProcessesKeyword_4_1_0; }
		
		//BEGIN
		public RuleCall getBEGINTerminalRuleCall_4_1_1() { return cBEGINTerminalRuleCall_4_1_1; }
		
		//processes+=Process*
		public Assignment getProcessesAssignment_4_1_2() { return cProcessesAssignment_4_1_2; }
		
		//Process
		public RuleCall getProcessesProcessParserRuleCall_4_1_2_0() { return cProcessesProcessParserRuleCall_4_1_2_0; }
		
		//END
		public RuleCall getENDTerminalRuleCall_4_1_3() { return cENDTerminalRuleCall_4_1_3; }
		
		//('nodes:'
		//    BEGIN
		//    components+=RosNode*
		//    END
		//)
		public Group getGroup_4_2() { return cGroup_4_2; }
		
		//'nodes:'
		public Keyword getNodesKeyword_4_2_0() { return cNodesKeyword_4_2_0; }
		
		//BEGIN
		public RuleCall getBEGINTerminalRuleCall_4_2_1() { return cBEGINTerminalRuleCall_4_2_1; }
		
		//components+=RosNode*
		public Assignment getComponentsAssignment_4_2_2() { return cComponentsAssignment_4_2_2; }
		
		//RosNode
		public RuleCall getComponentsRosNodeParserRuleCall_4_2_2_0() { return cComponentsRosNodeParserRuleCall_4_2_2_0; }
		
		//END
		public RuleCall getENDTerminalRuleCall_4_2_3() { return cENDTerminalRuleCall_4_2_3; }
		
		//('parameters:'
		//    BEGIN
		//    parameter+=Parameter*
		//    END
		//)
		public Group getGroup_4_3() { return cGroup_4_3; }
		
		//'parameters:'
		public Keyword getParametersKeyword_4_3_0() { return cParametersKeyword_4_3_0; }
		
		//BEGIN
		public RuleCall getBEGINTerminalRuleCall_4_3_1() { return cBEGINTerminalRuleCall_4_3_1; }
		
		//parameter+=Parameter*
		public Assignment getParameterAssignment_4_3_2() { return cParameterAssignment_4_3_2; }
		
		//Parameter
		public RuleCall getParameterParameterParserRuleCall_4_3_2_0() { return cParameterParameterParserRuleCall_4_3_2_0; }
		
		//END
		public RuleCall getENDTerminalRuleCall_4_3_3() { return cENDTerminalRuleCall_4_3_3; }
		
		//('connections:'
		//    BEGIN
		//    connections+=Connection*
		//    END
		//)
		public Group getGroup_4_4() { return cGroup_4_4; }
		
		//'connections:'
		public Keyword getConnectionsKeyword_4_4_0() { return cConnectionsKeyword_4_4_0; }
		
		//BEGIN
		public RuleCall getBEGINTerminalRuleCall_4_4_1() { return cBEGINTerminalRuleCall_4_4_1; }
		
		//connections+=Connection*
		public Assignment getConnectionsAssignment_4_4_2() { return cConnectionsAssignment_4_4_2; }
		
		//Connection
		public RuleCall getConnectionsConnectionParserRuleCall_4_4_2_0() { return cConnectionsConnectionParserRuleCall_4_4_2_0; }
		
		//END
		public RuleCall getENDTerminalRuleCall_4_4_3() { return cENDTerminalRuleCall_4_4_3; }
		
		//END
		public RuleCall getENDTerminalRuleCall_5() { return cENDTerminalRuleCall_5; }
	}
	public class RosParameterElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "eu.coresense.variability.Variability.RosParameter");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cHyphenMinusKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameEStringParserRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cColonKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cFromAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final CrossReference cFromParameterCrossReference_3_0 = (CrossReference)cFromAssignment_3.eContents().get(0);
		private final RuleCall cFromParameterEStringParserRuleCall_3_0_1 = (RuleCall)cFromParameterCrossReference_3_0.eContents().get(1);
		private final RuleCall cBEGINTerminalRuleCall_4 = (RuleCall)cGroup.eContents().get(4);
		private final Keyword cVariableValuesKeyword_5 = (Keyword)cGroup.eContents().get(5);
		private final Group cGroup_6 = (Group)cGroup.eContents().get(6);
		private final Keyword cLeftSquareBracketKeyword_6_0 = (Keyword)cGroup_6.eContents().get(0);
		private final Assignment cValueAssignment_6_1 = (Assignment)cGroup_6.eContents().get(1);
		private final RuleCall cValueParameterValueParserRuleCall_6_1_0 = (RuleCall)cValueAssignment_6_1.eContents().get(0);
		private final Group cGroup_6_2 = (Group)cGroup_6.eContents().get(2);
		private final Keyword cCommaKeyword_6_2_0 = (Keyword)cGroup_6_2.eContents().get(0);
		private final Assignment cValueAssignment_6_2_1 = (Assignment)cGroup_6_2.eContents().get(1);
		private final RuleCall cValueParameterValueParserRuleCall_6_2_1_0 = (RuleCall)cValueAssignment_6_2_1.eContents().get(0);
		private final Keyword cRightSquareBracketKeyword_6_3 = (Keyword)cGroup_6.eContents().get(3);
		private final RuleCall cENDTerminalRuleCall_7 = (RuleCall)cGroup.eContents().get(7);
		
		//@Override
		//RosParameter returns RosParameter:
		//    '-' name=EString':' from=[ros::Parameter|EString]
		//    BEGIN
		//    'variable values:' ('['value=ParameterValue (',' value=ParameterValue)*']')?
		//    END
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//'-' name=EString':' from=[ros::Parameter|EString]
		//BEGIN
		//'variable values:' ('['value=ParameterValue (',' value=ParameterValue)*']')?
		//END
		public Group getGroup() { return cGroup; }
		
		//'-'
		public Keyword getHyphenMinusKeyword_0() { return cHyphenMinusKeyword_0; }
		
		//name=EString
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_1_0() { return cNameEStringParserRuleCall_1_0; }
		
		//':'
		public Keyword getColonKeyword_2() { return cColonKeyword_2; }
		
		//from=[ros::Parameter|EString]
		public Assignment getFromAssignment_3() { return cFromAssignment_3; }
		
		//[ros::Parameter|EString]
		public CrossReference getFromParameterCrossReference_3_0() { return cFromParameterCrossReference_3_0; }
		
		//EString
		public RuleCall getFromParameterEStringParserRuleCall_3_0_1() { return cFromParameterEStringParserRuleCall_3_0_1; }
		
		//BEGIN
		public RuleCall getBEGINTerminalRuleCall_4() { return cBEGINTerminalRuleCall_4; }
		
		//'variable values:'
		public Keyword getVariableValuesKeyword_5() { return cVariableValuesKeyword_5; }
		
		//('['value=ParameterValue (',' value=ParameterValue)*']')?
		public Group getGroup_6() { return cGroup_6; }
		
		//'['
		public Keyword getLeftSquareBracketKeyword_6_0() { return cLeftSquareBracketKeyword_6_0; }
		
		//value=ParameterValue
		public Assignment getValueAssignment_6_1() { return cValueAssignment_6_1; }
		
		//ParameterValue
		public RuleCall getValueParameterValueParserRuleCall_6_1_0() { return cValueParameterValueParserRuleCall_6_1_0; }
		
		//(',' value=ParameterValue)*
		public Group getGroup_6_2() { return cGroup_6_2; }
		
		//','
		public Keyword getCommaKeyword_6_2_0() { return cCommaKeyword_6_2_0; }
		
		//value=ParameterValue
		public Assignment getValueAssignment_6_2_1() { return cValueAssignment_6_2_1; }
		
		//ParameterValue
		public RuleCall getValueParameterValueParserRuleCall_6_2_1_0() { return cValueParameterValueParserRuleCall_6_2_1_0; }
		
		//']'
		public Keyword getRightSquareBracketKeyword_6_3() { return cRightSquareBracketKeyword_6_3; }
		
		//END
		public RuleCall getENDTerminalRuleCall_7() { return cENDTerminalRuleCall_7; }
	}
	
	
	private final SystemElements pSystem;
	private final RosSystemElements pRosSystem;
	private final RosParameterElements pRosParameter;
	
	private final Grammar grammar;
	
	private final RosSystemGrammarAccess gaRosSystem;
	
	private final BasicsGrammarAccess gaBasics;
	
	private final TerminalsGrammarAccess gaTerminals;

	@Inject
	public VariabilityGrammarAccess(GrammarProvider grammarProvider,
			RosSystemGrammarAccess gaRosSystem,
			BasicsGrammarAccess gaBasics,
			TerminalsGrammarAccess gaTerminals) {
		this.grammar = internalFindGrammar(grammarProvider);
		this.gaRosSystem = gaRosSystem;
		this.gaBasics = gaBasics;
		this.gaTerminals = gaTerminals;
		this.pSystem = new SystemElements();
		this.pRosSystem = new RosSystemElements();
		this.pRosParameter = new RosParameterElements();
	}
	
	protected Grammar internalFindGrammar(GrammarProvider grammarProvider) {
		Grammar grammar = grammarProvider.getGrammar(this);
		while (grammar != null) {
			if ("eu.coresense.variability.Variability".equals(grammar.getName())) {
				return grammar;
			}
			List<Grammar> grammars = grammar.getUsedGrammars();
			if (!grammars.isEmpty()) {
				grammar = grammars.iterator().next();
			} else {
				return null;
			}
		}
		return grammar;
	}
	
	@Override
	public Grammar getGrammar() {
		return grammar;
	}
	
	
	public RosSystemGrammarAccess getRosSystemGrammarAccess() {
		return gaRosSystem;
	}
	
	public BasicsGrammarAccess getBasicsGrammarAccess() {
		return gaBasics;
	}
	
	public TerminalsGrammarAccess getTerminalsGrammarAccess() {
		return gaTerminals;
	}

	
	//System returns System:
	//    RosSystem
	//;
	public SystemElements getSystemAccess() {
		return pSystem;
	}
	
	public ParserRule getSystemRule() {
		return getSystemAccess().getRule();
	}
	
	//RosSystem returns System:
	//    name=EString':'
	//    BEGIN
	//        ('fromFile:' fromFile=EString)?
	//        (
	//        ('subSystems:'
	//            BEGIN
	//            components+=SubSystem*
	//            END
	//        ) |
	//        ('processes:'
	//            BEGIN
	//            processes+=Process*
	//            END
	//        ) |
	//        ('nodes:'
	//            BEGIN
	//            components+=RosNode*
	//            END
	//        ) |
	//        ('parameters:'
	//            BEGIN
	//            parameter+=Parameter*
	//            END
	//        ) |
	//        ('connections:'
	//            BEGIN
	//            connections+=Connection*
	//            END
	//        )
	//        )*
	//    END;
	public RosSystemElements getRosSystemAccess() {
		return pRosSystem;
	}
	
	public ParserRule getRosSystemRule() {
		return getRosSystemAccess().getRule();
	}
	
	//@Override
	//RosParameter returns RosParameter:
	//    '-' name=EString':' from=[ros::Parameter|EString]
	//    BEGIN
	//    'variable values:' ('['value=ParameterValue (',' value=ParameterValue)*']')?
	//    END
	//;
	public RosParameterElements getRosParameterAccess() {
		return pRosParameter;
	}
	
	public ParserRule getRosParameterRule() {
		return getRosParameterAccess().getRule();
	}
	
	//SubSystem returns SubSystem:
	//    system=[System|EString]
	//;
	public RosSystemGrammarAccess.SubSystemElements getSubSystemAccess() {
		return gaRosSystem.getSubSystemAccess();
	}
	
	public ParserRule getSubSystemRule() {
		return getSubSystemAccess().getRule();
	}
	
	//Process returns Process:
	//    {Process}
	//      name=EString':'
	//      BEGIN
	//      ('nodes:' '['components+=[RosNode|EString] (',' components+=[RosNode|EString])*']')?
	//      ('threads:'threads=Integer0)?
	//      END
	//;
	public RosSystemGrammarAccess.ProcessElements getProcessAccess() {
		return gaRosSystem.getProcessAccess();
	}
	
	public ParserRule getProcessRule() {
		return getProcessAccess().getRule();
	}
	
	//RosNode returns RosNode:
	//    {RosNode}
	//    name=EString':'
	//    BEGIN
	//    'from:'from=[ros::Node|EString]
	//    ('namespace:' namespace=EString)?
	//    ('interfaces:'
	//        BEGIN
	//            rosinterfaces+=RosInterface*
	//        END)?
	//    ('parameters:'
	//        BEGIN
	//            rosparameters+=RosParameter*
	//        END)?
	//    END
	//;
	public RosSystemGrammarAccess.RosNodeElements getRosNodeAccess() {
		return gaRosSystem.getRosNodeAccess();
	}
	
	public ParserRule getRosNodeRule() {
		return getRosNodeAccess().getRule();
	}
	
	//RosInterface returns RosInterface:
	//    '-'name=EString':' (reference=InterfaceReference)
	//;
	public RosSystemGrammarAccess.RosInterfaceElements getRosInterfaceAccess() {
		return gaRosSystem.getRosInterfaceAccess();
	}
	
	public ParserRule getRosInterfaceRule() {
		return getRosInterfaceAccess().getRule();
	}
	
	//InterfaceReference returns InterfaceReference:
	//    RosPublisherReference |
	//    RosSubscriberReference |
	//    RosServiceServerReference |
	//    RosServerClientReference |
	//    RosActionServerReference |
	//    RosActionClientReference;
	public RosSystemGrammarAccess.InterfaceReferenceElements getInterfaceReferenceAccess() {
		return gaRosSystem.getInterfaceReferenceAccess();
	}
	
	public ParserRule getInterfaceReferenceRule() {
		return getInterfaceReferenceAccess().getRule();
	}
	
	//RosPublisherReference returns RosPublisherReference:
	//    "pub->" {RosPublisherReference} from=[ros::Publisher|EString]
	//;
	public RosSystemGrammarAccess.RosPublisherReferenceElements getRosPublisherReferenceAccess() {
		return gaRosSystem.getRosPublisherReferenceAccess();
	}
	
	public ParserRule getRosPublisherReferenceRule() {
		return getRosPublisherReferenceAccess().getRule();
	}
	
	//RosSubscriberReference returns RosSubscriberReference:
	//    "sub->" {RosSubscriberReference} from=[ros::Subscriber|EString]
	//;
	public RosSystemGrammarAccess.RosSubscriberReferenceElements getRosSubscriberReferenceAccess() {
		return gaRosSystem.getRosSubscriberReferenceAccess();
	}
	
	public ParserRule getRosSubscriberReferenceRule() {
		return getRosSubscriberReferenceAccess().getRule();
	}
	
	//RosServiceServerReference returns RosServiceServerReference:
	//    "ss->" {RosServiceServerReference} from=[ros::ServiceServer|EString]
	//;
	public RosSystemGrammarAccess.RosServiceServerReferenceElements getRosServiceServerReferenceAccess() {
		return gaRosSystem.getRosServiceServerReferenceAccess();
	}
	
	public ParserRule getRosServiceServerReferenceRule() {
		return getRosServiceServerReferenceAccess().getRule();
	}
	
	//RosServerClientReference returns RosServiceClientReference:
	//    "sc->" {RosServiceClientReference} from=[ros::ServiceClient|EString]
	//;
	public RosSystemGrammarAccess.RosServerClientReferenceElements getRosServerClientReferenceAccess() {
		return gaRosSystem.getRosServerClientReferenceAccess();
	}
	
	public ParserRule getRosServerClientReferenceRule() {
		return getRosServerClientReferenceAccess().getRule();
	}
	
	//RosActionServerReference returns RosActionServerReference:
	//    "as->" {RosActionServerReference} from=[ros::ActionServer|EString]
	//;
	public RosSystemGrammarAccess.RosActionServerReferenceElements getRosActionServerReferenceAccess() {
		return gaRosSystem.getRosActionServerReferenceAccess();
	}
	
	public ParserRule getRosActionServerReferenceRule() {
		return getRosActionServerReferenceAccess().getRule();
	}
	
	//RosActionClientReference returns RosActionClientReference:
	//    "ac->" {RosActionClientReference} from=[ros::ActionClient|EString]
	//;
	public RosSystemGrammarAccess.RosActionClientReferenceElements getRosActionClientReferenceAccess() {
		return gaRosSystem.getRosActionClientReferenceAccess();
	}
	
	public ParserRule getRosActionClientReferenceRule() {
		return getRosActionClientReferenceAccess().getRule();
	}
	
	////By default the grammar will parser RosSystemConnection, i.e., connections of ports
	//// explicitly referenced within the system model. RosConnections are also implemented but not used for now.
	//Connection returns Connection:
	//    ( => RosSystemConnection) | RosConnection
	//;
	public RosSystemGrammarAccess.ConnectionElements getConnectionAccess() {
		return gaRosSystem.getConnectionAccess();
	}
	
	public ParserRule getConnectionRule() {
		return getConnectionAccess().getRule();
	}
	
	//RosSystemConnection returns RosSystemConnection:
	//    '-''['from=[RosInterface|EString]','to=[RosInterface|EString]']'
	//;
	public RosSystemGrammarAccess.RosSystemConnectionElements getRosSystemConnectionAccess() {
		return gaRosSystem.getRosSystemConnectionAccess();
	}
	
	public ParserRule getRosSystemConnectionRule() {
		return getRosSystemConnectionAccess().getRule();
	}
	
	//RosConnection returns RosConnection:
	//    ( => RosTopicConnection) | ( => RosServiceConnection) | RosActionConnection
	//;
	public RosSystemGrammarAccess.RosConnectionElements getRosConnectionAccess() {
		return gaRosSystem.getRosConnectionAccess();
	}
	
	public ParserRule getRosConnectionRule() {
		return getRosConnectionAccess().getRule();
	}
	
	//RosTopicConnection returns RosTopicConnection:
	//    '-''['from=[ros::Publisher|EString]','to=[ros::Subscriber|EString]']'
	//;
	public RosSystemGrammarAccess.RosTopicConnectionElements getRosTopicConnectionAccess() {
		return gaRosSystem.getRosTopicConnectionAccess();
	}
	
	public ParserRule getRosTopicConnectionRule() {
		return getRosTopicConnectionAccess().getRule();
	}
	
	//RosServiceConnection returns RosServiceConnection:
	//    '-''['from=[ros::ServiceServer|EString]','to=[ros::ServiceClient|EString]']'
	//;
	public RosSystemGrammarAccess.RosServiceConnectionElements getRosServiceConnectionAccess() {
		return gaRosSystem.getRosServiceConnectionAccess();
	}
	
	public ParserRule getRosServiceConnectionRule() {
		return getRosServiceConnectionAccess().getRule();
	}
	
	//RosActionConnection returns RosActionConnection:
	//    '-''['from=[ros::ActionServer|EString]','to=[ros::ActionClient|EString]']'
	//;
	public RosSystemGrammarAccess.RosActionConnectionElements getRosActionConnectionAccess() {
		return gaRosSystem.getRosActionConnectionAccess();
	}
	
	public ParserRule getRosActionConnectionRule() {
		return getRosActionConnectionAccess().getRule();
	}
	
	/////////////////////
	////NAMESPACES
	/////////////////////
	//Namespace returns Namespace:
	//    GlobalNamespace | RelativeNamespace_Impl | PrivateNamespace;
	public BasicsGrammarAccess.NamespaceElements getNamespaceAccess() {
		return gaBasics.getNamespaceAccess();
	}
	
	public ParserRule getNamespaceRule() {
		return getNamespaceAccess().getRule();
	}
	
	//GraphName returns GraphName:
	//    'GraphName' ;
	public BasicsGrammarAccess.GraphNameElements getGraphNameAccess() {
		return gaBasics.getGraphNameAccess();
	}
	
	public ParserRule getGraphNameRule() {
		return getGraphNameAccess().getRule();
	}
	
	//GlobalNamespace returns GlobalNamespace:
	//    {GlobalNamespace}
	//    'GlobalNamespace'
	//        ('[' parts+=GraphName ( "," parts+=GraphName)* ']' )?;
	public BasicsGrammarAccess.GlobalNamespaceElements getGlobalNamespaceAccess() {
		return gaBasics.getGlobalNamespaceAccess();
	}
	
	public ParserRule getGlobalNamespaceRule() {
		return getGlobalNamespaceAccess().getRule();
	}
	
	//RelativeNamespace_Impl returns RelativeNamespace:
	//    {RelativeNamespace}
	//    'RelativeNamespace'
	//        ('[' parts+=GraphName ( "," parts+=GraphName)* ']' )?;
	public BasicsGrammarAccess.RelativeNamespace_ImplElements getRelativeNamespace_ImplAccess() {
		return gaBasics.getRelativeNamespace_ImplAccess();
	}
	
	public ParserRule getRelativeNamespace_ImplRule() {
		return getRelativeNamespace_ImplAccess().getRule();
	}
	
	//PrivateNamespace returns PrivateNamespace:
	//    {PrivateNamespace}
	//    'PrivateNamespace'
	//        ('[' parts+=GraphName ( "," parts+=GraphName)* ']' )?;
	public BasicsGrammarAccess.PrivateNamespaceElements getPrivateNamespaceAccess() {
		return gaBasics.getPrivateNamespaceAccess();
	}
	
	public ParserRule getPrivateNamespaceRule() {
		return getPrivateNamespaceAccess().getRule();
	}
	
	/////////////////////
	////PARAMETERS DEFINITION
	/////////////////////
	//RosParamNames returns ecore::EString:
	//    ROS_CONVENTION_PARAM | ID
	//;
	public BasicsGrammarAccess.RosParamNamesElements getRosParamNamesAccess() {
		return gaBasics.getRosParamNamesAccess();
	}
	
	public ParserRule getRosParamNamesRule() {
		return getRosParamNamesAccess().getRule();
	}
	
	//Parameter returns Parameter:
	//    {Parameter}
	//        name=EString':'
	//        BEGIN
	//        ('ns:' namespace=Namespace)?
	//        'type:' type=ParameterType
	//        ('value:' value=ParameterValue)?
	//        END
	//    ;
	public BasicsGrammarAccess.ParameterElements getParameterAccess() {
		return gaBasics.getParameterAccess();
	}
	
	public ParserRule getParameterRule() {
		return getParameterAccess().getRule();
	}
	
	//ParameterType returns ParameterType:
	//    ParameterListType | ParameterStructType | ParameterIntegerType | ParameterStringType | ParameterDoubleType | ParameterBooleanType | ParameterBase64Type | ParameterArrayType;
	public BasicsGrammarAccess.ParameterTypeElements getParameterTypeAccess() {
		return gaBasics.getParameterTypeAccess();
	}
	
	public ParserRule getParameterTypeRule() {
		return getParameterTypeAccess().getRule();
	}
	
	// // | ParameterDateType;
	//ParameterValue returns ParameterValue:
	//    ParameterString | ParameterBase64 | ParameterInteger | ParameterDouble | ParameterBoolean | ParameterList | ParameterStruct;
	public BasicsGrammarAccess.ParameterValueElements getParameterValueAccess() {
		return gaBasics.getParameterValueAccess();
	}
	
	public ParserRule getParameterValueRule() {
		return getParameterValueAccess().getRule();
	}
	
	// // | ParameterDate;
	//ParameterListType returns ParameterListType:
	//    {ParameterListType}
	//    'List'
	//    '['
	//        sequence+=ParameterType ( ',' sequence+=ParameterType )*
	//    ']';
	public BasicsGrammarAccess.ParameterListTypeElements getParameterListTypeAccess() {
		return gaBasics.getParameterListTypeAccess();
	}
	
	public ParserRule getParameterListTypeRule() {
		return getParameterListTypeAccess().getRule();
	}
	
	//ParameterStructType returns ParameterStructType:
	//    {ParameterStructType}
	//    'Struct'
	//    '['
	//        parameterstructypetmember+=ParameterStructTypeMember ( "," parameterstructypetmember+=ParameterStructTypeMember)*
	//    ']';
	public BasicsGrammarAccess.ParameterStructTypeElements getParameterStructTypeAccess() {
		return gaBasics.getParameterStructTypeAccess();
	}
	
	public ParserRule getParameterStructTypeRule() {
		return getParameterStructTypeAccess().getRule();
	}
	
	//ParameterIntegerType returns ParameterIntegerType:
	//    {ParameterIntegerType}
	//    'Integer'
	//    ('default:' default=ParameterInteger)?;
	public BasicsGrammarAccess.ParameterIntegerTypeElements getParameterIntegerTypeAccess() {
		return gaBasics.getParameterIntegerTypeAccess();
	}
	
	public ParserRule getParameterIntegerTypeRule() {
		return getParameterIntegerTypeAccess().getRule();
	}
	
	//ParameterStringType returns ParameterStringType:
	//    {ParameterStringType}
	//    'String'
	//    ('default:' default=ParameterString)?;
	public BasicsGrammarAccess.ParameterStringTypeElements getParameterStringTypeAccess() {
		return gaBasics.getParameterStringTypeAccess();
	}
	
	public ParserRule getParameterStringTypeRule() {
		return getParameterStringTypeAccess().getRule();
	}
	
	//ParameterDoubleType returns ParameterDoubleType:
	//    {ParameterDoubleType}
	//    'Double'
	//    ('default:' default=ParameterDouble)?;
	public BasicsGrammarAccess.ParameterDoubleTypeElements getParameterDoubleTypeAccess() {
		return gaBasics.getParameterDoubleTypeAccess();
	}
	
	public ParserRule getParameterDoubleTypeRule() {
		return getParameterDoubleTypeAccess().getRule();
	}
	
	//ParameterDateType returns ParameterDateType:
	//    {ParameterDateType}
	//    'Date'
	//    ('default:' default=ParameterDate)?;
	public BasicsGrammarAccess.ParameterDateTypeElements getParameterDateTypeAccess() {
		return gaBasics.getParameterDateTypeAccess();
	}
	
	public ParserRule getParameterDateTypeRule() {
		return getParameterDateTypeAccess().getRule();
	}
	
	//ParameterBooleanType returns ParameterBooleanType:
	//    {ParameterBooleanType}
	//    'Boolean'
	//    ('default:' default=ParameterBoolean)?;
	public BasicsGrammarAccess.ParameterBooleanTypeElements getParameterBooleanTypeAccess() {
		return gaBasics.getParameterBooleanTypeAccess();
	}
	
	public ParserRule getParameterBooleanTypeRule() {
		return getParameterBooleanTypeAccess().getRule();
	}
	
	//ParameterBase64Type returns ParameterBase64Type:
	//    {ParameterBase64Type}
	//    'Base64'
	//    ('default:' default=ParameterBase64)?;
	public BasicsGrammarAccess.ParameterBase64TypeElements getParameterBase64TypeAccess() {
		return gaBasics.getParameterBase64TypeAccess();
	}
	
	public ParserRule getParameterBase64TypeRule() {
		return getParameterBase64TypeAccess().getRule();
	}
	
	//ParameterAnyType returns ParameterAnyType:
	//    {ParameterAnyType}
	//    'Any'
	//    ('default:' default=ParameterAny)?;
	public BasicsGrammarAccess.ParameterAnyTypeElements getParameterAnyTypeAccess() {
		return gaBasics.getParameterAnyTypeAccess();
	}
	
	public ParserRule getParameterAnyTypeRule() {
		return getParameterAnyTypeAccess().getRule();
	}
	
	//ParameterArrayType returns ParameterArrayType:
	//    'Array' '[' type=ParameterType ']'
	//    ('default:' default=ParameterList)?
	//;
	public BasicsGrammarAccess.ParameterArrayTypeElements getParameterArrayTypeAccess() {
		return gaBasics.getParameterArrayTypeAccess();
	}
	
	public ParserRule getParameterArrayTypeRule() {
		return getParameterArrayTypeAccess().getRule();
	}
	
	//ParameterList returns ParameterSequence:
	//    {ParameterSequence}
	//        '[' value+=ParameterValue ( ',' value+=ParameterValue )* ']'
	//;
	public BasicsGrammarAccess.ParameterListElements getParameterListAccess() {
		return gaBasics.getParameterListAccess();
	}
	
	public ParserRule getParameterListRule() {
		return getParameterListAccess().getRule();
	}
	
	//ParameterAny returns ParameterAny:
	//    {ParameterAny}
	//    'ParameterAny'
	//        ('value' value=EString)?
	//    ;
	public BasicsGrammarAccess.ParameterAnyElements getParameterAnyAccess() {
		return gaBasics.getParameterAnyAccess();
	}
	
	public ParserRule getParameterAnyRule() {
		return getParameterAnyAccess().getRule();
	}
	
	//ParameterString returns ParameterString:
	//    value=EString
	//;
	public BasicsGrammarAccess.ParameterStringElements getParameterStringAccess() {
		return gaBasics.getParameterStringAccess();
	}
	
	public ParserRule getParameterStringRule() {
		return getParameterStringAccess().getRule();
	}
	
	//ParameterBase64 returns ParameterBase64:
	//    value=Base64Binary
	//;
	public BasicsGrammarAccess.ParameterBase64Elements getParameterBase64Access() {
		return gaBasics.getParameterBase64Access();
	}
	
	public ParserRule getParameterBase64Rule() {
		return getParameterBase64Access().getRule();
	}
	
	//ParameterInteger returns ParameterInteger:
	//    value=Integer0
	//;
	public BasicsGrammarAccess.ParameterIntegerElements getParameterIntegerAccess() {
		return gaBasics.getParameterIntegerAccess();
	}
	
	public ParserRule getParameterIntegerRule() {
		return getParameterIntegerAccess().getRule();
	}
	
	//ParameterDouble returns ParameterDouble:
	//    value=Double0
	//;
	public BasicsGrammarAccess.ParameterDoubleElements getParameterDoubleAccess() {
		return gaBasics.getParameterDoubleAccess();
	}
	
	public ParserRule getParameterDoubleRule() {
		return getParameterDoubleAccess().getRule();
	}
	
	//ParameterBoolean returns ParameterBoolean:
	//    value=boolean0
	//;
	public BasicsGrammarAccess.ParameterBooleanElements getParameterBooleanAccess() {
		return gaBasics.getParameterBooleanAccess();
	}
	
	public ParserRule getParameterBooleanRule() {
		return getParameterBooleanAccess().getRule();
	}
	
	//ParameterStruct returns ParameterStruct:
	//    {ParameterStruct}
	//        ('['
	//        BEGIN
	//        (value+=ParameterStructMember)* ']'
	//        END
	//        )?
	//;
	public BasicsGrammarAccess.ParameterStructElements getParameterStructAccess() {
		return gaBasics.getParameterStructAccess();
	}
	
	public ParserRule getParameterStructRule() {
		return getParameterStructAccess().getRule();
	}
	
	//ParameterDate returns ParameterDate:
	//    value=DateTime0
	//    ;
	public BasicsGrammarAccess.ParameterDateElements getParameterDateAccess() {
		return gaBasics.getParameterDateAccess();
	}
	
	public ParserRule getParameterDateRule() {
		return getParameterDateAccess().getRule();
	}
	
	//ParameterStructMember returns ParameterStructMember:
	//    name=EString':'value=ParameterValue;
	public BasicsGrammarAccess.ParameterStructMemberElements getParameterStructMemberAccess() {
		return gaBasics.getParameterStructMemberAccess();
	}
	
	public ParserRule getParameterStructMemberRule() {
		return getParameterStructMemberAccess().getRule();
	}
	
	//ParameterStructTypeMember returns ParameterStructTypeMember:
	//        name=EString
	//        type=ParameterType
	//    ;
	public BasicsGrammarAccess.ParameterStructTypeMemberElements getParameterStructTypeMemberAccess() {
		return gaBasics.getParameterStructTypeMemberAccess();
	}
	
	public ParserRule getParameterStructTypeMemberRule() {
		return getParameterStructTypeMemberAccess().getRule();
	}
	
	/////////////////////
	////PARAMETERS PRIMITIVES TYPES
	/////////////////////
	//terminal DIGIT: '0'..'9';
	public TerminalRule getDIGITRule() {
		return gaBasics.getDIGITRule();
	}
	
	//terminal BINARY: ('0b'|'0B')('0'|'1')+;
	public TerminalRule getBINARYRule() {
		return gaBasics.getBINARYRule();
	}
	
	//terminal BOOLEAN: 'true'|'false';
	public TerminalRule getBOOLEANRule() {
		return gaBasics.getBOOLEANRule();
	}
	
	//terminal DOUBLE returns ecore::EDouble: (DIGIT* | ('-' DIGIT*) ) (('.' DECINT*) | (('.' DIGIT*)? ('E'|'e') ('-'|'+')? DIGIT*));
	public TerminalRule getDOUBLERule() {
		return gaBasics.getDOUBLERule();
	}
	
	//  // Use terminal to avoid 'e' turning into a keyword
	//terminal DECINT: '0' | ('1'..'9' DIGIT*) | ('-''0'..'9' DIGIT*) ;
	public TerminalRule getDECINTRule() {
		return gaBasics.getDECINTRule();
	}
	
	//terminal DAY:'1'..'9' | '1'..'3' '0'..'9';
	public TerminalRule getDAYRule() {
		return gaBasics.getDAYRule();
	}
	
	//terminal MONTH:'1'..'9' | '1' '0'..'2';
	public TerminalRule getMONTHRule() {
		return gaBasics.getMONTHRule();
	}
	
	//terminal YEAR:'0'..'2' '0'..'9' '0'..'9' '0'..'9';
	public TerminalRule getYEARRule() {
		return gaBasics.getYEARRule();
	}
	
	//terminal HOUR: ('0'..'1')('0'..'9') | ('2')('0'..'3');
	public TerminalRule getHOURRule() {
		return gaBasics.getHOURRule();
	}
	
	//terminal MIN_SEC:('0'..'5')('0'..'9');
	public TerminalRule getMIN_SECRule() {
		return gaBasics.getMIN_SECRule();
	}
	
	//terminal DATE_TIME: YEAR'-'MONTH'-'DAY'T'HOUR':'MIN_SEC':'MIN_SEC;
	public TerminalRule getDATE_TIMERule() {
		return gaBasics.getDATE_TIMERule();
	}
	
	//Base64Binary returns type::Base64Binary:
	//    BINARY ;
	public BasicsGrammarAccess.Base64BinaryElements getBase64BinaryAccess() {
		return gaBasics.getBase64BinaryAccess();
	}
	
	public ParserRule getBase64BinaryRule() {
		return getBase64BinaryAccess().getRule();
	}
	
	//boolean0 returns type::Boolean:
	//    BOOLEAN;
	public BasicsGrammarAccess.Boolean0Elements getBoolean0Access() {
		return gaBasics.getBoolean0Access();
	}
	
	public ParserRule getBoolean0Rule() {
		return getBoolean0Access().getRule();
	}
	
	//Double0 returns type::Double:
	//    DOUBLE;
	public BasicsGrammarAccess.Double0Elements getDouble0Access() {
		return gaBasics.getDouble0Access();
	}
	
	public ParserRule getDouble0Rule() {
		return getDouble0Access().getRule();
	}
	
	//Integer0 returns type::Int:
	//    DECINT;
	public BasicsGrammarAccess.Integer0Elements getInteger0Access() {
		return gaBasics.getInteger0Access();
	}
	
	public ParserRule getInteger0Rule() {
		return getInteger0Access().getRule();
	}
	
	//DateTime0 returns type::DateTime:
	//    DATE_TIME;
	public BasicsGrammarAccess.DateTime0Elements getDateTime0Access() {
		return gaBasics.getDateTime0Access();
	}
	
	public ParserRule getDateTime0Rule() {
		return getDateTime0Access().getRule();
	}
	
	/////////////////////
	////MESSAGE PRIMITIVES DEFINITION
	/////////////////////
	//MessagePart returns primitives::MessagePart:
	//    Type = AbstractType
	//    Data =(KEYWORD | MESSAGE_ASIGMENT | EString)
	//;
	public BasicsGrammarAccess.MessagePartElements getMessagePartAccess() {
		return gaBasics.getMessagePartAccess();
	}
	
	public ParserRule getMessagePartRule() {
		return getMessagePartAccess().getRule();
	}
	
	//terminal MESSAGE_ASIGMENT:
	//    ((ID|STRING)'='(ID|STRING|INT|'-'INT))
	//;
	public TerminalRule getMESSAGE_ASIGMENTRule() {
		return gaBasics.getMESSAGE_ASIGMENTRule();
	}
	
	//AbstractType returns primitives::AbstractType:
	//    bool | int8 | uint8 | int16 | uint16 | int32 | uint32 | int64 | uint64 | float32 | float64 | string0 | byte | time | duration | Header |
	//    boolArray | int8Array | uint8Array | int16Array | uint16Array | int32Array | uint32Array | int64Array | uint64Array | float32Array | float64Array | string0Array | byteArray |
	//    SpecBaseRef | ArraySpecRef | char | charArray;
	public BasicsGrammarAccess.AbstractTypeElements getAbstractTypeAccess() {
		return gaBasics.getAbstractTypeAccess();
	}
	
	public ParserRule getAbstractTypeRule() {
		return getAbstractTypeAccess().getRule();
	}
	
	//bool returns primitives::bool:
	//    {primitives::bool}
	//    'bool'
	//    ;
	public BasicsGrammarAccess.BoolElements getBoolAccess() {
		return gaBasics.getBoolAccess();
	}
	
	public ParserRule getBoolRule() {
		return getBoolAccess().getRule();
	}
	
	//int8 returns primitives::int8:
	//    {primitives::int8}
	//    'int8'
	//    ;
	public BasicsGrammarAccess.Int8Elements getInt8Access() {
		return gaBasics.getInt8Access();
	}
	
	public ParserRule getInt8Rule() {
		return getInt8Access().getRule();
	}
	
	//uint8 returns primitives::uint8:
	//    {primitives::uint8}
	//    'uint8'
	//    ;
	public BasicsGrammarAccess.Uint8Elements getUint8Access() {
		return gaBasics.getUint8Access();
	}
	
	public ParserRule getUint8Rule() {
		return getUint8Access().getRule();
	}
	
	//int16 returns primitives::int16:
	//    {primitives::int16}
	//    'int16'
	//    ;
	public BasicsGrammarAccess.Int16Elements getInt16Access() {
		return gaBasics.getInt16Access();
	}
	
	public ParserRule getInt16Rule() {
		return getInt16Access().getRule();
	}
	
	//uint16 returns primitives::uint16:
	//    {primitives::uint16}
	//    'uint16'
	//    ;
	public BasicsGrammarAccess.Uint16Elements getUint16Access() {
		return gaBasics.getUint16Access();
	}
	
	public ParserRule getUint16Rule() {
		return getUint16Access().getRule();
	}
	
	//int32 returns primitives::int32:
	//    {primitives::int32}
	//    'int32'
	//    ;
	public BasicsGrammarAccess.Int32Elements getInt32Access() {
		return gaBasics.getInt32Access();
	}
	
	public ParserRule getInt32Rule() {
		return getInt32Access().getRule();
	}
	
	//uint32 returns primitives::uint32:
	//    {primitives::uint32}
	//    'uint32'
	//    ;
	public BasicsGrammarAccess.Uint32Elements getUint32Access() {
		return gaBasics.getUint32Access();
	}
	
	public ParserRule getUint32Rule() {
		return getUint32Access().getRule();
	}
	
	//int64 returns primitives::int64:
	//    {primitives::int64}
	//    'int64'
	//    ;
	public BasicsGrammarAccess.Int64Elements getInt64Access() {
		return gaBasics.getInt64Access();
	}
	
	public ParserRule getInt64Rule() {
		return getInt64Access().getRule();
	}
	
	//uint64 returns primitives::uint64:
	//    {primitives::uint64}
	//    'uint64'
	//    ;
	public BasicsGrammarAccess.Uint64Elements getUint64Access() {
		return gaBasics.getUint64Access();
	}
	
	public ParserRule getUint64Rule() {
		return getUint64Access().getRule();
	}
	
	//float32 returns primitives::float32:
	//    {primitives::float32}
	//    'float32'
	//    ;
	public BasicsGrammarAccess.Float32Elements getFloat32Access() {
		return gaBasics.getFloat32Access();
	}
	
	public ParserRule getFloat32Rule() {
		return getFloat32Access().getRule();
	}
	
	//float64 returns primitives::float64:
	//    {primitives::float64}
	//    'float64'
	//    ;
	public BasicsGrammarAccess.Float64Elements getFloat64Access() {
		return gaBasics.getFloat64Access();
	}
	
	public ParserRule getFloat64Rule() {
		return getFloat64Access().getRule();
	}
	
	//string0 returns primitives::string:
	//    {primitives::string}
	//    'string'
	//    ;
	public BasicsGrammarAccess.String0Elements getString0Access() {
		return gaBasics.getString0Access();
	}
	
	public ParserRule getString0Rule() {
		return getString0Access().getRule();
	}
	
	//char returns primitives::char0:
	//    {primitives::char0}
	//    'char'
	//    ;
	public BasicsGrammarAccess.CharElements getCharAccess() {
		return gaBasics.getCharAccess();
	}
	
	public ParserRule getCharRule() {
		return getCharAccess().getRule();
	}
	
	//byte returns primitives::Byte:
	//    {primitives::Byte}
	//    'byte'
	//    ;
	public BasicsGrammarAccess.ByteElements getByteAccess() {
		return gaBasics.getByteAccess();
	}
	
	public ParserRule getByteRule() {
		return getByteAccess().getRule();
	}
	
	//time returns primitives::time:
	//    {primitives::time}
	//    'time'
	//    ;
	public BasicsGrammarAccess.TimeElements getTimeAccess() {
		return gaBasics.getTimeAccess();
	}
	
	public ParserRule getTimeRule() {
		return getTimeAccess().getRule();
	}
	
	//duration returns primitives::duration:
	//    {primitives::duration}
	//    'duration'
	//    ;
	public BasicsGrammarAccess.DurationElements getDurationAccess() {
		return gaBasics.getDurationAccess();
	}
	
	public ParserRule getDurationRule() {
		return getDurationAccess().getRule();
	}
	
	//boolArray returns primitives::boolArray:
	//    {primitives::boolArray}
	//    'bool[]'
	//    ;
	public BasicsGrammarAccess.BoolArrayElements getBoolArrayAccess() {
		return gaBasics.getBoolArrayAccess();
	}
	
	public ParserRule getBoolArrayRule() {
		return getBoolArrayAccess().getRule();
	}
	
	//int8Array returns primitives::int8Array:
	//    {primitives::int8Array}
	//    'int8[]'
	//    ;
	public BasicsGrammarAccess.Int8ArrayElements getInt8ArrayAccess() {
		return gaBasics.getInt8ArrayAccess();
	}
	
	public ParserRule getInt8ArrayRule() {
		return getInt8ArrayAccess().getRule();
	}
	
	//uint8Array returns primitives::uint8Array:
	//    {primitives::uint8Array}
	//    'uint8[]'
	//    ;
	public BasicsGrammarAccess.Uint8ArrayElements getUint8ArrayAccess() {
		return gaBasics.getUint8ArrayAccess();
	}
	
	public ParserRule getUint8ArrayRule() {
		return getUint8ArrayAccess().getRule();
	}
	
	//int16Array returns primitives::int16Array:
	//    {primitives::int16Array}
	//    'int16[]'
	//    ;
	public BasicsGrammarAccess.Int16ArrayElements getInt16ArrayAccess() {
		return gaBasics.getInt16ArrayAccess();
	}
	
	public ParserRule getInt16ArrayRule() {
		return getInt16ArrayAccess().getRule();
	}
	
	//uint16Array returns primitives::uint16Array:
	//    {primitives::uint16Array}
	//    'uint16[]'
	//    ;
	public BasicsGrammarAccess.Uint16ArrayElements getUint16ArrayAccess() {
		return gaBasics.getUint16ArrayAccess();
	}
	
	public ParserRule getUint16ArrayRule() {
		return getUint16ArrayAccess().getRule();
	}
	
	//int32Array returns primitives::int32Array:
	//    {primitives::int32Array}
	//    'int32[]'
	//    ;
	public BasicsGrammarAccess.Int32ArrayElements getInt32ArrayAccess() {
		return gaBasics.getInt32ArrayAccess();
	}
	
	public ParserRule getInt32ArrayRule() {
		return getInt32ArrayAccess().getRule();
	}
	
	//uint32Array returns primitives::uint32Array:
	//    {primitives::uint32Array}
	//    'uint32[]'
	//    ;
	public BasicsGrammarAccess.Uint32ArrayElements getUint32ArrayAccess() {
		return gaBasics.getUint32ArrayAccess();
	}
	
	public ParserRule getUint32ArrayRule() {
		return getUint32ArrayAccess().getRule();
	}
	
	//int64Array returns primitives::int64Array:
	//    {primitives::int64Array}
	//    'int64[]'
	//    ;
	public BasicsGrammarAccess.Int64ArrayElements getInt64ArrayAccess() {
		return gaBasics.getInt64ArrayAccess();
	}
	
	public ParserRule getInt64ArrayRule() {
		return getInt64ArrayAccess().getRule();
	}
	
	//uint64Array returns primitives::uint64Array:
	//    {primitives::uint64Array}
	//    'uint64[]'
	//    ;
	public BasicsGrammarAccess.Uint64ArrayElements getUint64ArrayAccess() {
		return gaBasics.getUint64ArrayAccess();
	}
	
	public ParserRule getUint64ArrayRule() {
		return getUint64ArrayAccess().getRule();
	}
	
	//float32Array returns primitives::float32Array:
	//    {primitives::float32Array}
	//    'float32[]'
	//    ;
	public BasicsGrammarAccess.Float32ArrayElements getFloat32ArrayAccess() {
		return gaBasics.getFloat32ArrayAccess();
	}
	
	public ParserRule getFloat32ArrayRule() {
		return getFloat32ArrayAccess().getRule();
	}
	
	//float64Array returns primitives::float64Array:
	//    {primitives::float64Array}
	//    'float64[]'
	//    ;
	public BasicsGrammarAccess.Float64ArrayElements getFloat64ArrayAccess() {
		return gaBasics.getFloat64ArrayAccess();
	}
	
	public ParserRule getFloat64ArrayRule() {
		return getFloat64ArrayAccess().getRule();
	}
	
	//string0Array returns primitives::stringArray:
	//    {primitives::stringArray}
	//    'string[]'
	//    ;
	public BasicsGrammarAccess.String0ArrayElements getString0ArrayAccess() {
		return gaBasics.getString0ArrayAccess();
	}
	
	public ParserRule getString0ArrayRule() {
		return getString0ArrayAccess().getRule();
	}
	
	//byteArray returns primitives::ByteArray:
	//    {primitives::ByteArray}
	//    'byte[]'
	//    ;
	public BasicsGrammarAccess.ByteArrayElements getByteArrayAccess() {
		return gaBasics.getByteArrayAccess();
	}
	
	public ParserRule getByteArrayRule() {
		return getByteArrayAccess().getRule();
	}
	
	//charArray returns primitives::charArray:
	//    {primitives::charArray}
	//    'char[]'
	//    ;
	public BasicsGrammarAccess.CharArrayElements getCharArrayAccess() {
		return gaBasics.getCharArrayAccess();
	}
	
	public ParserRule getCharArrayRule() {
		return getCharArrayAccess().getRule();
	}
	
	//Header returns primitives::Header:
	//    {primitives::Header}
	//    'Header'
	//;
	public BasicsGrammarAccess.HeaderElements getHeaderAccess() {
		return gaBasics.getHeaderAccess();
	}
	
	public ParserRule getHeaderRule() {
		return getHeaderAccess().getRule();
	}
	
	//SpecBaseRef returns TopicSpecMsgRef:
	//    Reference=[TopicSpec|EString]
	//;
	public BasicsGrammarAccess.SpecBaseRefElements getSpecBaseRefAccess() {
		return gaBasics.getSpecBaseRefAccess();
	}
	
	public ParserRule getSpecBaseRefRule() {
		return getSpecBaseRefAccess().getRule();
	}
	
	//ArraySpecRef returns ArrayTopicSpecMsgRef:
	//    Reference=[TopicSpec|EString]'[]'
	//;
	public BasicsGrammarAccess.ArraySpecRefElements getArraySpecRefAccess() {
		return gaBasics.getArraySpecRefAccess();
	}
	
	public ParserRule getArraySpecRefRule() {
		return getArraySpecRefAccess().getRule();
	}
	
	//KEYWORD: 'goal' | 'message' | 'result' | 'feedback' | 'name' | 'value' | 'service' | 'type' | 'action' | 'duration' | 'time'  ;
	public BasicsGrammarAccess.KEYWORDElements getKEYWORDAccess() {
		return gaBasics.getKEYWORDAccess();
	}
	
	public ParserRule getKEYWORDRule() {
		return getKEYWORDAccess().getRule();
	}
	
	/////////////////////
	//// YAML format
	/////////////////////
	//terminal BEGIN: 'synthetic:BEGIN';
	public TerminalRule getBEGINRule() {
		return gaBasics.getBEGINRule();
	}
	
	//terminal END: 'synthetic:END';
	public TerminalRule getENDRule() {
		return gaBasics.getENDRule();
	}
	
	//@Override
	//terminal SL_COMMENT: '#' !('\n'|'\r')*;
	public TerminalRule getSL_COMMENTRule() {
		return gaBasics.getSL_COMMENTRule();
	}
	
	/////////////////////
	//// CONVENTIONS AND NAMES
	/////////////////////
	//EString returns ecore::EString:
	//    STRING | ID;
	public BasicsGrammarAccess.EStringElements getEStringAccess() {
		return gaBasics.getEStringAccess();
	}
	
	public ParserRule getEStringRule() {
		return getEStringAccess().getRule();
	}
	
	//RosNames returns ecore::EString:
	//    ROS_CONVENTION_A | ID | 'node'
	//;
	public BasicsGrammarAccess.RosNamesElements getRosNamesAccess() {
		return gaBasics.getRosNamesAccess();
	}
	
	public ParserRule getRosNamesRule() {
		return getRosNamesAccess().getRule();
	}
	
	//terminal ROS_CONVENTION_A:
	//    ( ('/' ID ) | ( ID '/' ) )* ;
	public TerminalRule getROS_CONVENTION_ARule() {
		return gaBasics.getROS_CONVENTION_ARule();
	}
	
	//terminal ROS_CONVENTION_PARAM:
	//    ( ('/' STRING ) | ( STRING '/' ) | ('~' STRING ) )* ;
	public TerminalRule getROS_CONVENTION_PARAMRule() {
		return gaBasics.getROS_CONVENTION_PARAMRule();
	}
	
	//terminal ID: '^'?('a'..'z'|'A'..'Z'|'_') ('a'..'z'|'A'..'Z'|'_'|'0'..'9')*;
	public TerminalRule getIDRule() {
		return gaTerminals.getIDRule();
	}
	
	//terminal INT returns ecore::EInt: ('0'..'9')+;
	public TerminalRule getINTRule() {
		return gaTerminals.getINTRule();
	}
	
	//terminal STRING:
	//            '"' ( '\\' . /* 'b'|'t'|'n'|'f'|'r'|'u'|'"'|"'"|'\\' */ | !('\\'|'"') )* '"' |
	//            "'" ( '\\' . /* 'b'|'t'|'n'|'f'|'r'|'u'|'"'|"'"|'\\' */ | !('\\'|"'") )* "'"
	//        ;
	public TerminalRule getSTRINGRule() {
		return gaTerminals.getSTRINGRule();
	}
	
	//terminal ML_COMMENT : '/*' -> '*/';
	public TerminalRule getML_COMMENTRule() {
		return gaTerminals.getML_COMMENTRule();
	}
	
	//terminal WS         : (' '|'\t'|'\r'|'\n')+;
	public TerminalRule getWSRule() {
		return gaTerminals.getWSRule();
	}
	
	//terminal ANY_OTHER: .;
	public TerminalRule getANY_OTHERRule() {
		return gaTerminals.getANY_OTHERRule();
	}
}
