/*
 * generated by Xtext 2.38.0
 */
package eu.coresense.variability.scoping;

import de.fraunhofer.ipa.rossystem.scoping.RosSystemScopeProvider;

public abstract class AbstractVariabilityScopeProvider extends RosSystemScopeProvider {
}
